### ISSUE TITLE
calling Java varargs method (e.g. String.format) generates wrong descriptor — arguments not packed into array, return type inferred as Object

### ISSUE THREAD

**Issue by PublioSantos** [KofLang/Kof4j#216]
## Description

When calling a Java standard-library method that uses varargs (e.g. `String.format(String, Object...)`), the compiler:

1. **Does not pack the extra arguments into an `Object[]` array** — each argument is passed as a separate parameter in the descriptor.
2. **Infers the return type as `Object`** instead of the actual return type (`String` for `String.format`).

The resulting `invokestatic` descriptor does not match any real method, causing a **NoSuchMethodError** at runtime.

## Minimal reproduction

```kof
main() {
    var s = String.format("Hello %s, age %d", "Alice", 30)
    println(s)
}
```

**Runtime output:**
```
Exception in thread "main" java.lang.NoSuchMethodError:
  'java.lang.Object java.lang.String.format(java.lang.String, java.lang.String, int)'
```

## Bytecode (javap -c)

```
invokestatic #17  // Method java/lang/String.format:(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;
```

**Generated descriptor:** `(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;`
**Correct descriptor:** `(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;`

Two errors in the generated descriptor:
- Extra args passed individually instead of packed into `[Ljava/lang/Object;`
- Return type is `Ljava/lang/Object;` instead of `Ljava/lang/String;`

## Additional variant (zero extra args)

```kof
var s = String.format("Hello World")   // NoSuchMethodError: String.format(String)
```

The compiler generates `(Ljava/lang/String;)Ljava/lang/String;` — a non-existent single-arg overload — instead of the varargs form `(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;`.

## Note

Non-varargs `String` instance methods such as `toUpperCase()`, `substring()`, and `contains()` resolve correctly. The issue is specific to Java varargs methods called from Kof.

## Environment

Kof 0.4.0-beta, JVM target
By: Bug Hunter

**Comment by melmonfre** [comment]
REPRODUZ no HEAD `6e2cdb12`, medido 14/09 ~11:20: `String.format("Hello %s, age %d", "Alice", 30)` → `NoSuchMethodError: java.lang.Object String.format(...)` — o call interop não empacota o rabo varargs em `Object[]` e infer `Object` como retorno (real: `(String,Object[])→String`). Catalogado **§210** no known-bugs (pointer: lowering de MethodCall com `isVarArgs()` + `anewarray`). R6 violado (compila, nunca roda) — mesma família da #156/§166. Lane compiler.

**Comment by melmonfre** [comment]
Fixed in `042916c1` (branch `beta-0.4.0`).

This is the same root as #156. Both reported errors in the descriptor were real:

- extra args were passed individually instead of packed into `[Ljava/lang/Object;`
- the return type was inferred as `Ljava/lang/Object;` instead of `Ljava/lang/String;`

**Root cause:** `ExternalClasspath.findDeclared`/`resolveMethod` match overloads by **name+arity only**, with no `ACC_VARARGS` handling, and `java.lang.String` is not among the classpath entries — so the builtin-receiver branch of `ExpressionMethodCallLowerer` fell through to a fabricated descriptor.

**Fix (root cause):** new `StringFormatCallLowerer` builds an `Object[]` sized to the extra args (primitives boxed), emits `DUP`/`IASTORE` per element, and emits the REAL descriptor:

```
invokestatic java/lang/String.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
```

The zero-extra-args variant (`String.format("Hello World")`) is covered too — it previously emitted the nonexistent `(Ljava/lang/String;)Ljava/lang/String;` overload.

**Proof (same commit):** `StringFormatVarargsE2ETest` 9/9, proven **red on the pre-fix code** (`aa78eba0`/`d6eaae0c`) with the exact `NoSuchMethodError`.

**Known residual (catalogued §239, JS lane):** the KofJS backend has no `String.format` lowering (pre-existing `COMP002`); the test is intentionally JVM-only.
